
let C,S={view:'home',cat:null,map:null,page:0,q:'',fav:JSON.parse(localStorage.getItem('bm:fav')||'[]'),recent:JSON.parse(localStorage.getItem('bm:recent')||'[]')};
const save=()=>{localStorage.setItem('bm:fav',JSON.stringify(S.fav));localStorage.setItem('bm:recent',JSON.stringify(S.recent.slice(0,20)))};
const card=m=>`<button class="card" data-map="${m.id}"><div class="thumb">${m.icon}</div><h3>${m.title}${S.fav.includes(m.id)?' ★':''}</h3><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></button>`;
const shell=x=>`<div class="shell"><header class="top"><button class="back" id="back">${S.view==='home'?'':'← Voltar'}</button><div class="brand">Biblio<span>ME</span></div><button class="back" id="favtop">★ Favoritos</button></header><main class="main">${x}</main><nav class="bottom">${[['home','⌂','Início'],['favorites','☆','Favoritos'],['recent','◷','Recentes'],['search','⌕','Buscar'],['more','•••','Mais']].map(n=>`<button data-nav="${n[0]}" class="${S.view===n[0]?'active':''}">${n[1]}<br>${n[2]}</button>`).join('')}</nav></div>`;
function home(){let q=C.quick.map(id=>C.maps.find(m=>m.id===id));return shell(`<section class="hero"><h1>O que você precisa consultar <span>hoje?</span></h1><p>Mapas visuais para decisões rápidas no plantão.</p></section><div class="search"><input id="gs" placeholder="Buscar infográficos, protocolos, drogas, procedimentos..."><button id="gob">Buscar</button></div><h2>⚡ Consulta Rápida</h2><div class="quick">${q.map(m=>`<button class="card" data-map="${m.id}"><div class="ico">${m.icon}</div><h3>${m.title}</h3></button>`).join('')}</div><h2>Categorias</h2><div class="cats">${C.categories.map(c=>`<button class="card" data-cat="${c.id}"><div class="ico">${c.icon}</div><h3>${c.name}</h3><p>${c.description}</p></button>`).join('')}</div>`) }
function cat(){let c=C.categories.find(x=>x.id===S.cat),maps=C.maps.filter(m=>m.category===S.cat);return shell(`<div class="cathead"><div class="ico">${c.icon}</div><div><h1>${c.name}</h1><p>${c.description}</p></div></div><div class="search"><input id="cs" placeholder="Buscar na categoria ${c.name}..."></div><div class="grid" id="mg">${maps.map(card).join('')}</div>`) }
function viewer(){let m=C.maps.find(x=>x.id===S.map);if(!S.recent.includes(m.id))S.recent.unshift(m.id);else S.recent=[m.id,...S.recent.filter(x=>x!==m.id)];save();return shell(`<div style="display:flex;justify-content:space-between;align-items:center"><div><small>${C.categories.find(c=>c.id===m.category)?.name||''}</small><h1>${m.title}</h1></div><button class="pill" id="tf">${S.fav.includes(m.id)?'★ Favorito':'☆ Favoritar'}</button></div><div class="viewer"><div class="thumbs">${m.pages.map((p,i)=>`<button class="thumbbtn ${i===S.page?'active':''}" data-page="${i}">${i+1}. ${p}</button>`).join('')}</div><div class="viewerbox"><div class="viewerimg"><div><div style="font-size:60px">${m.icon}</div><h2>${m.pages[S.page]}</h2><p>Placeholder do infográfico real</p></div></div><div class="actions"><button id="prev">← Anterior</button><span>${S.page+1}/${m.pages.length}</span><button id="next" class="primary">Próximo →</button></div></div></div>`) }
function list(type){let ids=type==='favorites'?S.fav:S.recent,title=type==='favorites'?'Favoritos':'Recentes',maps=ids.map(id=>C.maps.find(m=>m.id===id)).filter(Boolean);return shell(`<h1>${title}</h1><div class="grid">${maps.map(card).join('')}</div>`) }
function search(){let q=S.q.toLowerCase(),maps=q?C.maps.filter(m=>[m.title,...m.tags].join(' ').toLowerCase().includes(q)):C.maps;return shell(`<h1>Buscar</h1><div class="search"><input id="sp" value="${S.q}" placeholder="Ex.: noradrenalina, AVC, RUSH"><button id="sb">Buscar</button></div><div class="grid">${maps.map(card).join('')}</div>`) }
function render(){let a=document.getElementById('app');a.innerHTML=S.view==='home'?home():S.view==='category'?cat():S.view==='viewer'?viewer():['favorites','recent'].includes(S.view)?list(S.view):S.view==='search'?search():shell('<h2>Em breve.</h2>');bind()}
function bind(){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;S.view='category';render()});document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{S.map=b.dataset.map;S.page=0;S.view='viewer';render()});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{S.view=b.dataset.nav;render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=+b.dataset.page;render()});let back=document.getElementById('back');if(back&&S.view!=='home')back.onclick=()=>{if(S.view==='viewer'){S.cat=C.maps.find(m=>m.id===S.map).category;S.view='category'}else S.view='home';render()};document.getElementById('favtop').onclick=()=>{S.view='favorites';render()};let gs=document.getElementById('gs'),gob=document.getElementById('gob');if(gob)gob.onclick=()=>{S.q=gs.value;S.view='search';render()};let cs=document.getElementById('cs');if(cs)cs.oninput=()=>document.querySelectorAll('#mg .card').forEach(el=>{let m=C.maps.find(x=>x.id===el.dataset.map);el.style.display=[m.title,...m.tags].join(' ').toLowerCase().includes(cs.value.toLowerCase())?'':'none'});let tf=document.getElementById('tf');if(tf)tf.onclick=()=>{S.fav.includes(S.map)?S.fav=S.fav.filter(x=>x!==S.map):S.fav.unshift(S.map);save();render()};let m=C.maps.find(x=>x.id===S.map),p=document.getElementById('prev'),n=document.getElementById('next');if(p)p.onclick=()=>{S.page=Math.max(0,S.page-1);render()};if(n)n.onclick=()=>{S.page=Math.min(m.pages.length-1,S.page+1);render()};let sp=document.getElementById('sp'),sb=document.getElementById('sb');if(sb)sb.onclick=()=>{S.q=sp.value;render()}}
fetch('./catalog.json').then(r=>r.json()).then(c=>{C=c;render()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
